// Code generated by minigo-gen-bindings. DO NOT EDIT.

package strings

import (
	"strings"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "strings" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("strings", map[string]any{
		"Clone":          strings.Clone,
		"Compare":        strings.Compare,
		"Lines":          strings.Lines,
		"SplitSeq":       strings.SplitSeq,
		"SplitAfterSeq":  strings.SplitAfterSeq,
		"FieldsSeq":      strings.FieldsSeq,
		"FieldsFuncSeq":  strings.FieldsFuncSeq,
		"NewReader":      strings.NewReader,
		"NewReplacer":    strings.NewReplacer,
		"Count":          strings.Count,
		"Contains":       strings.Contains,
		"ContainsAny":    strings.ContainsAny,
		"ContainsRune":   strings.ContainsRune,
		"ContainsFunc":   strings.ContainsFunc,
		"LastIndex":      strings.LastIndex,
		"IndexByte":      strings.IndexByte,
		"IndexRune":      strings.IndexRune,
		"IndexAny":       strings.IndexAny,
		"LastIndexAny":   strings.LastIndexAny,
		"LastIndexByte":  strings.LastIndexByte,
		"SplitN":         strings.SplitN,
		"SplitAfterN":    strings.SplitAfterN,
		"Split":          strings.Split,
		"SplitAfter":     strings.SplitAfter,
		"Fields":         strings.Fields,
		"FieldsFunc":     strings.FieldsFunc,
		"Join":           strings.Join,
		"HasPrefix":      strings.HasPrefix,
		"HasSuffix":      strings.HasSuffix,
		"Map":            strings.Map,
		"Repeat":         strings.Repeat,
		"ToUpper":        strings.ToUpper,
		"ToLower":        strings.ToLower,
		"ToTitle":        strings.ToTitle,
		"ToUpperSpecial": strings.ToUpperSpecial,
		"ToLowerSpecial": strings.ToLowerSpecial,
		"ToTitleSpecial": strings.ToTitleSpecial,
		"ToValidUTF8":    strings.ToValidUTF8,
		"Title":          strings.Title,
		"TrimLeftFunc":   strings.TrimLeftFunc,
		"TrimRightFunc":  strings.TrimRightFunc,
		"TrimFunc":       strings.TrimFunc,
		"IndexFunc":      strings.IndexFunc,
		"LastIndexFunc":  strings.LastIndexFunc,
		"Trim":           strings.Trim,
		"TrimLeft":       strings.TrimLeft,
		"TrimRight":      strings.TrimRight,
		"TrimSpace":      strings.TrimSpace,
		"TrimPrefix":     strings.TrimPrefix,
		"TrimSuffix":     strings.TrimSuffix,
		"Replace":        strings.Replace,
		"ReplaceAll":     strings.ReplaceAll,
		"EqualFold":      strings.EqualFold,
		"Index":          strings.Index,
		"Cut":            strings.Cut,
		"CutPrefix":      strings.CutPrefix,
		"CutSuffix":      strings.CutSuffix,
	})
}
