// Code generated by minigo-gen-bindings. DO NOT EDIT.

package strings

import (
	"strings"
	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "strings" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("strings", map[string]any{
		"Clone": strings.Clone,
		"Compare": strings.Compare,
		"Contains": strings.Contains,
		"ContainsAny": strings.ContainsAny,
		"ContainsFunc": strings.ContainsFunc,
		"ContainsRune": strings.ContainsRune,
		"Count": strings.Count,
		"Cut": strings.Cut,
		"CutPrefix": strings.CutPrefix,
		"CutSuffix": strings.CutSuffix,
		"EqualFold": strings.EqualFold,
		"Fields": strings.Fields,
		"FieldsFunc": strings.FieldsFunc,
		"FieldsFuncSeq": strings.FieldsFuncSeq,
		"FieldsSeq": strings.FieldsSeq,
		"HasPrefix": strings.HasPrefix,
		"HasSuffix": strings.HasSuffix,
		"Index": strings.Index,
		"IndexAny": strings.IndexAny,
		"IndexByte": strings.IndexByte,
		"IndexFunc": strings.IndexFunc,
		"IndexRune": strings.IndexRune,
		"Join": strings.Join,
		"LastIndex": strings.LastIndex,
		"LastIndexAny": strings.LastIndexAny,
		"LastIndexByte": strings.LastIndexByte,
		"LastIndexFunc": strings.LastIndexFunc,
		"Lines": strings.Lines,
		"Map": strings.Map,
		"NewReader": strings.NewReader,
		"NewReplacer": strings.NewReplacer,
		"Repeat": strings.Repeat,
		"Replace": strings.Replace,
		"ReplaceAll": strings.ReplaceAll,
		"Split": strings.Split,
		"SplitAfter": strings.SplitAfter,
		"SplitAfterN": strings.SplitAfterN,
		"SplitAfterSeq": strings.SplitAfterSeq,
		"SplitN": strings.SplitN,
		"SplitSeq": strings.SplitSeq,
		"Title": strings.Title,
		"ToLower": strings.ToLower,
		"ToLowerSpecial": strings.ToLowerSpecial,
		"ToTitle": strings.ToTitle,
		"ToTitleSpecial": strings.ToTitleSpecial,
		"ToUpper": strings.ToUpper,
		"ToUpperSpecial": strings.ToUpperSpecial,
		"ToValidUTF8": strings.ToValidUTF8,
		"Trim": strings.Trim,
		"TrimFunc": strings.TrimFunc,
		"TrimLeft": strings.TrimLeft,
		"TrimLeftFunc": strings.TrimLeftFunc,
		"TrimPrefix": strings.TrimPrefix,
		"TrimRight": strings.TrimRight,
		"TrimRightFunc": strings.TrimRightFunc,
		"TrimSpace": strings.TrimSpace,
		"TrimSuffix": strings.TrimSuffix,
	})
}
