// Code generated by minigo-gen-bindings. DO NOT EDIT.

package errors

import (
	"errors"
	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "errors" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("errors", map[string]any{
		"As": errors.As,
		"ErrUnsupported": errors.ErrUnsupported,
		"Is": errors.Is,
		"Join": errors.Join,
		"New": errors.New,
		"Unwrap": errors.Unwrap,
	})
}
