// Code generated by minigo-gen-bindings. DO NOT EDIT.

package url

import (
	"net/url"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "net/url" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("net/url", map[string]any{
		"UserPassword":    url.UserPassword,
		"Parse":           url.Parse,
		"ParseRequestURI": url.ParseRequestURI,
		"QueryUnescape":   url.QueryUnescape,
		"PathUnescape":    url.PathUnescape,
		"QueryEscape":     url.QueryEscape,
		"PathEscape":      url.PathEscape,
		"User":            url.User,
		"ParseQuery":      url.ParseQuery,
		"JoinPath":        url.JoinPath,
	})
}
