// Code generated by minigo-gen-bindings. DO NOT EDIT.

package fmt

import (
	"fmt"
	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "fmt" package to the interpreter.
func Install(interp *minigo.Interpreter, installed map[string]bool) {
	if installed["fmt"] {
		return
	}
	installed["fmt"] = true

	interp.Register("fmt", map[string]any{
		"Sscan": fmt.Sscan,
		"Sscanln": fmt.Sscanln,
		"Sscanf": fmt.Sscanf,
		"Appendln": fmt.Appendln,
		"Fprintf": fmt.Fprintf,
		"Sprint": fmt.Sprint,
		"Fprintln": fmt.Fprintln,
		"Println": fmt.Println,
		"Scanln": fmt.Scanln,
		"Fscan": fmt.Fscan,
		"Scan": fmt.Scan,
		"Fscanln": fmt.Fscanln,
		"Fscanf": fmt.Fscanf,
		"Sprintln": fmt.Sprintln,
		"Errorf": fmt.Errorf,
		"FormatString": fmt.FormatString,
		"Appendf": fmt.Appendf,
		"Fprint": fmt.Fprint,
		"Scanf": fmt.Scanf,
		"Printf": fmt.Printf,
		"Sprintf": fmt.Sprintf,
		"Print": fmt.Print,
		"Append": fmt.Append,
	})
}
