// Code generated by minigo-gen-bindings. DO NOT EDIT.

package fmt

import (
	"fmt"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "fmt" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("fmt", map[string]any{
		"Sprintf":      fmt.Sprintf,
		"Errorf":       fmt.Errorf,
		"Sscan":        fmt.Sscan,
		"Sscanf":       fmt.Sscanf,
		"Fprintf":      fmt.Fprintf,
		"Fprintln":     fmt.Fprintln,
		"Appendln":     fmt.Appendln,
		"Fscanln":      fmt.Fscanln,
		"Fscanf":       fmt.Fscanf,
		"Printf":       fmt.Printf,
		"Fprint":       fmt.Fprint,
		"Sprint":       fmt.Sprint,
		"Scan":         fmt.Scan,
		"Scanln":       fmt.Scanln,
		"Sscanln":      fmt.Sscanln,
		"Fscan":        fmt.Fscan,
		"Println":      fmt.Println,
		"Sprintln":     fmt.Sprintln,
		"Scanf":        fmt.Scanf,
		"FormatString": fmt.FormatString,
		"Appendf":      fmt.Appendf,
		"Print":        fmt.Print,
		"Append":       fmt.Append,
	})
}
