// Code generated by minigo-gen-bindings. DO NOT EDIT.

package template

import (
	"text/template"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "text/template" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("text/template", map[string]any{
		"HTMLEscape":       template.HTMLEscape,
		"HTMLEscaper":      template.HTMLEscaper,
		"JSEscaper":        template.JSEscaper,
		"URLQueryEscaper":  template.URLQueryEscaper,
		"New":              template.New,
		"ParseFiles":       template.ParseFiles,
		"ParseGlob":        template.ParseGlob,
		"ParseFS":          template.ParseFS,
		"HTMLEscapeString": template.HTMLEscapeString,
		"JSEscape":         template.JSEscape,
		"JSEscapeString":   template.JSEscapeString,
		"IsTrue":           template.IsTrue,
		"Must":             template.Must,
	})
}
