// Code generated by minigo-gen-bindings. DO NOT EDIT.

package rand

import (
	"math/rand"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "math/rand" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("math/rand", map[string]any{
		"Int31":       rand.Int31,
		"Int63n":      rand.Int63n,
		"Int31n":      rand.Int31n,
		"Intn":        rand.Intn,
		"Shuffle":     rand.Shuffle,
		"Read":        rand.Read,
		"Seed":        rand.Seed,
		"Int63":       rand.Int63,
		"Uint32":      rand.Uint32,
		"NormFloat64": rand.NormFloat64,
		"NewSource":   rand.NewSource,
		"Uint64":      rand.Uint64,
		"Int":         rand.Int,
		"Perm":        rand.Perm,
		"ExpFloat64":  rand.ExpFloat64,
		"NewZipf":     rand.NewZipf,
		"New":         rand.New,
		"Float64":     rand.Float64,
		"Float32":     rand.Float32,
	})
}
