// Code generated by minigo-gen-bindings. DO NOT EDIT.

package slices

import (
	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "slices" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	// No symbols to register for slices.
	// This is likely because the package only contains generic functions, which are not yet supported.
	interp.Register("slices", map[string]any{})
}
