// Code generated by go-scan for package anotherpkg. DO NOT EDIT.

package anotherpkg

import (
	"errors"
	"net/http"

	"github.com/podhmo/go-scan/examples/derivingbind/binding"
	"github.com/podhmo/go-scan/examples/derivingbind/parser"
)

func (s *AnotherModel) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.ItemName, binding.Query, "item_name", parser.String, binding.Required), // Field: ItemName (string)

		binding.OnePtr(b, &s.Quantity, binding.Query, "quantity", parser.Int, binding.Optional), // Field: Quantity (*int)

		binding.One(b, &s.IsSpecial, binding.Header, "X-Special", parser.Bool, binding.Optional), // Field: IsSpecial (bool)

	)
}
