// Code generated by minigo-gen-bindings. DO NOT EDIT.

package strconv

import (
	"strconv"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "strconv" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("strconv", map[string]any{
		"ParseBool":                strconv.ParseBool,
		"FormatBool":               strconv.FormatBool,
		"AppendBool":               strconv.AppendBool,
		"ParseComplex":             strconv.ParseComplex,
		"FormatComplex":            strconv.FormatComplex,
		"FormatUint":               strconv.FormatUint,
		"FormatInt":                strconv.FormatInt,
		"Itoa":                     strconv.Itoa,
		"AppendInt":                strconv.AppendInt,
		"AppendUint":               strconv.AppendUint,
		"ParseUint":                strconv.ParseUint,
		"ParseInt":                 strconv.ParseInt,
		"Atoi":                     strconv.Atoi,
		"Quote":                    strconv.Quote,
		"AppendQuote":              strconv.AppendQuote,
		"QuoteToASCII":             strconv.QuoteToASCII,
		"AppendQuoteToASCII":       strconv.AppendQuoteToASCII,
		"QuoteToGraphic":           strconv.QuoteToGraphic,
		"AppendQuoteToGraphic":     strconv.AppendQuoteToGraphic,
		"QuoteRune":                strconv.QuoteRune,
		"AppendQuoteRune":          strconv.AppendQuoteRune,
		"QuoteRuneToASCII":         strconv.QuoteRuneToASCII,
		"AppendQuoteRuneToASCII":   strconv.AppendQuoteRuneToASCII,
		"QuoteRuneToGraphic":       strconv.QuoteRuneToGraphic,
		"AppendQuoteRuneToGraphic": strconv.AppendQuoteRuneToGraphic,
		"CanBackquote":             strconv.CanBackquote,
		"UnquoteChar":              strconv.UnquoteChar,
		"QuotedPrefix":             strconv.QuotedPrefix,
		"Unquote":                  strconv.Unquote,
		"IsPrint":                  strconv.IsPrint,
		"IsGraphic":                strconv.IsGraphic,
		"FormatFloat":              strconv.FormatFloat,
		"AppendFloat":              strconv.AppendFloat,
		"ParseFloat":               strconv.ParseFloat,
		"IntSize":                  strconv.IntSize,
	})
}
