// Code generated by minigo-gen-bindings. DO NOT EDIT.

package io

import (
	"io"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "io" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("io", map[string]any{
		"WriteString":      io.WriteString,
		"CopyBuffer":       io.CopyBuffer,
		"LimitReader":      io.LimitReader,
		"ReadAll":          io.ReadAll,
		"Pipe":             io.Pipe,
		"NewSectionReader": io.NewSectionReader,
		"NewOffsetWriter":  io.NewOffsetWriter,
		"SeekCurrent":      io.SeekCurrent,
		"SeekEnd":          io.SeekEnd,
		"MultiWriter":      io.MultiWriter,
		"CopyN":            io.CopyN,
		"TeeReader":        io.TeeReader,
		"MultiReader":      io.MultiReader,
		"ReadAtLeast":      io.ReadAtLeast,
		"ReadFull":         io.ReadFull,
		"Copy":             io.Copy,
		"NopCloser":        io.NopCloser,
		"SeekStart":        io.SeekStart,
	})
}
