// Code generated by minigo-gen-bindings. DO NOT EDIT.

package io

import (
	"io"
	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "io" package to the interpreter.
func Install(interp *minigo.Interpreter, installed map[string]bool) {
	if installed["io"] {
		return
	}
	installed["io"] = true

	interp.Register("io", map[string]any{
		"NewOffsetWriter": io.NewOffsetWriter,
		"WriteString": io.WriteString,
		"NopCloser": io.NopCloser,
		"SeekStart": io.SeekStart,
		"SeekCurrent": io.SeekCurrent,
		"MultiWriter": io.MultiWriter,
		"ReadAtLeast": io.ReadAtLeast,
		"CopyBuffer": io.CopyBuffer,
		"LimitReader": io.LimitReader,
		"NewSectionReader": io.NewSectionReader,
		"ReadAll": io.ReadAll,
		"Pipe": io.Pipe,
		"MultiReader": io.MultiReader,
		"CopyN": io.CopyN,
		"TeeReader": io.TeeReader,
		"SeekEnd": io.SeekEnd,
		"ReadFull": io.ReadFull,
		"Copy": io.Copy,
	})
}
