// Code generated by minigo-gen-bindings. DO NOT EDIT.

package bytes

import (
	"bytes"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "bytes" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("bytes", map[string]any{
		"SplitAfterSeq":   bytes.SplitAfterSeq,
		"Equal":           bytes.Equal,
		"Contains":        bytes.Contains,
		"IndexAny":        bytes.IndexAny,
		"TrimSuffix":      bytes.TrimSuffix,
		"EqualFold":       bytes.EqualFold,
		"LastIndexAny":    bytes.LastIndexAny,
		"Join":            bytes.Join,
		"Repeat":          bytes.Repeat,
		"FieldsFuncSeq":   bytes.FieldsFuncSeq,
		"LastIndexFunc":   bytes.LastIndexFunc,
		"Compare":         bytes.Compare,
		"ToUpperSpecial":  bytes.ToUpperSpecial,
		"TrimLeftFunc":    bytes.TrimLeftFunc,
		"IndexFunc":       bytes.IndexFunc,
		"Count":           bytes.Count,
		"IndexRune":       bytes.IndexRune,
		"Title":           bytes.Title,
		"LastIndexByte":   bytes.LastIndexByte,
		"MinRead":         bytes.MinRead,
		"ContainsAny":     bytes.ContainsAny,
		"LastIndex":       bytes.LastIndex,
		"SplitAfterN":     bytes.SplitAfterN,
		"Fields":          bytes.Fields,
		"ToTitle":         bytes.ToTitle,
		"Runes":           bytes.Runes,
		"Clone":           bytes.Clone,
		"CutSuffix":       bytes.CutSuffix,
		"TrimRight":       bytes.TrimRight,
		"ReplaceAll":      bytes.ReplaceAll,
		"CutPrefix":       bytes.CutPrefix,
		"NewBuffer":       bytes.NewBuffer,
		"ContainsFunc":    bytes.ContainsFunc,
		"TrimLeft":        bytes.TrimLeft,
		"NewBufferString": bytes.NewBufferString,
		"HasPrefix":       bytes.HasPrefix,
		"Map":             bytes.Map,
		"TrimPrefix":      bytes.TrimPrefix,
		"FieldsSeq":       bytes.FieldsSeq,
		"ToUpper":         bytes.ToUpper,
		"ToLower":         bytes.ToLower,
		"TrimSpace":       bytes.TrimSpace,
		"NewReader":       bytes.NewReader,
		"SplitN":          bytes.SplitN,
		"ToValidUTF8":     bytes.ToValidUTF8,
		"SplitSeq":        bytes.SplitSeq,
		"Split":           bytes.Split,
		"FieldsFunc":      bytes.FieldsFunc,
		"ToLowerSpecial":  bytes.ToLowerSpecial,
		"TrimFunc":        bytes.TrimFunc,
		"Lines":           bytes.Lines,
		"ToTitleSpecial":  bytes.ToTitleSpecial,
		"Index":           bytes.Index,
		"Replace":         bytes.Replace,
		"Cut":             bytes.Cut,
		"ContainsRune":    bytes.ContainsRune,
		"IndexByte":       bytes.IndexByte,
		"SplitAfter":      bytes.SplitAfter,
		"HasSuffix":       bytes.HasSuffix,
		"TrimRightFunc":   bytes.TrimRightFunc,
		"Trim":            bytes.Trim,
	})
}
