// Code generated by minigo-gen-bindings. DO NOT EDIT.

package context

import (
	"context"
	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "context" package to the interpreter.
func Install(interp *minigo.Interpreter, installed map[string]bool) {
	if installed["context"] {
		return
	}
	installed["context"] = true

	interp.Register("context", map[string]any{
		"WithDeadlineCause": context.WithDeadlineCause,
		"WithCancel": context.WithCancel,
		"WithCancelCause": context.WithCancelCause,
		"Cause": context.Cause,
		"WithDeadline": context.WithDeadline,
		"WithTimeout": context.WithTimeout,
		"WithTimeoutCause": context.WithTimeoutCause,
		"WithValue": context.WithValue,
		"Background": context.Background,
		"TODO": context.TODO,
		"AfterFunc": context.AfterFunc,
		"WithoutCancel": context.WithoutCancel,
	})
}
