// Code generated by go-scan for package integrationtest. DO NOT EDIT.

package integrationtest

import (
	json "encoding/json"
)

func (s *Dog) MarshalJSON() ([]byte, error) {
	type Alias Dog
	return json.Marshal(&struct {
		*Alias
		Type string `json:"type"`
	}{
		Alias: (*Alias)(s),
		Type:  "dog",
	})
}

func (s *Cat) MarshalJSON() ([]byte, error) {
	type Alias Cat
	return json.Marshal(&struct {
		*Alias
		Type string `json:"type"`
	}{
		Alias: (*Alias)(s),
		Type:  "cat",
	})
}

func (s *Car) MarshalJSON() ([]byte, error) {
	type Alias Car
	return json.Marshal(&struct {
		*Alias
		Type string `json:"type"`
	}{
		Alias: (*Alias)(s),
		Type:  "car",
	})
}

func (s *Bicycle) MarshalJSON() ([]byte, error) {
	type Alias Bicycle
	return json.Marshal(&struct {
		*Alias
		Type string `json:"type"`
	}{
		Alias: (*Alias)(s),
		Type:  "bicycle",
	})
}

func (s *Goldfish) MarshalJSON() ([]byte, error) {
	type Alias Goldfish
	return json.Marshal(&struct {
		*Alias
		Type string `json:"type"`
	}{
		Alias: (*Alias)(s),
		Type:  "goldfish",
	})
}

func (s *UserProfile) MarshalJSON() ([]byte, error) {
	type Alias UserProfile
	return json.Marshal(&struct {
		*Alias
		Type string `json:"type"`
	}{
		Alias: (*Alias)(s),
		Type:  "userprofile",
	})
}

func (s *ProductInfo) MarshalJSON() ([]byte, error) {
	type Alias ProductInfo
	return json.Marshal(&struct {
		*Alias
		Type string `json:"type"`
	}{
		Alias: (*Alias)(s),
		Type:  "productinfo",
	})
}
