// Code generated by minigo-gen-bindings. DO NOT EDIT.

package list

import (
	"container/list"
	"reflect"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "container/list" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("container/list", map[string]any{
		"New":     list.New,
		"Element": reflect.TypeOf((*list.Element)(nil)).Elem(),
		"List":    reflect.TypeOf((*list.List)(nil)).Elem(),
	})
}
