// Code generated by minigo-gen-bindings. DO NOT EDIT.

package list

import (
	"container/list"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "container/list" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("container/list", map[string]any{
		"New":     list.New,
		"Element": (*list.Element)(nil),
		"List":    (*list.List)(nil),
	})
}
