// Code generated by derivingbind for package integrationtest. DO NOT EDIT.

package integrationtest

import (
	"errors"
	"github.com/podhmo/go-scan/examples/derivingbind/binding"
	"github.com/podhmo/go-scan/examples/derivingbind/parser"
	"net/http"
)

func (s *TestBindStringQueryOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Query, "value", parser.String, binding.Optional), // Field: Value (string)

	)
}

func (s *TestBindStringQueryRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Query, "value", parser.String, binding.Required), // Field: Value (string)

	)
}

func (s *TestBindPtrStringQueryOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Query, "value", parser.String, binding.Optional), // Field: Value (*string)

	)
}

func (s *TestBindPtrStringQueryRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Query, "value", parser.String, binding.Required), // Field: Value (*string)

	)
}

func (s *TestBindStringHeaderOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Header, "X-Value", parser.String, binding.Optional), // Field: Value (string)

	)
}

func (s *TestBindStringHeaderRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Header, "X-Value", parser.String, binding.Required), // Field: Value (string)

	)
}

func (s *TestBindPtrStringHeaderOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Header, "X-Value", parser.String, binding.Optional), // Field: Value (*string)

	)
}

func (s *TestBindPtrStringHeaderRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Header, "X-Value", parser.String, binding.Required), // Field: Value (*string)

	)
}

func (s *TestBindStringCookieOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Cookie, "value", parser.String, binding.Optional), // Field: Value (string)

	)
}

func (s *TestBindStringCookieRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Cookie, "value", parser.String, binding.Required), // Field: Value (string)

	)
}

func (s *TestBindPtrStringCookieOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Cookie, "value", parser.String, binding.Optional), // Field: Value (*string)

	)
}

func (s *TestBindPtrStringCookieRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Cookie, "value", parser.String, binding.Required), // Field: Value (*string)

	)
}

func (s *TestBindStringPathOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Path, "value", parser.String, binding.Optional), // Field: Value (string)

	)
}

func (s *TestBindStringPathRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Path, "value", parser.String, binding.Required), // Field: Value (string)

	)
}

func (s *TestBindPtrStringPathOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Path, "value", parser.String, binding.Optional), // Field: Value (*string)

	)
}

func (s *TestBindPtrStringPathRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Path, "value", parser.String, binding.Required), // Field: Value (*string)

	)
}

func (s *TestBindIntQueryOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Query, "value", parser.Int, binding.Optional), // Field: Value (int)

	)
}

func (s *TestBindIntQueryRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Query, "value", parser.Int, binding.Required), // Field: Value (int)

	)
}

func (s *TestBindPtrIntQueryOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Query, "value", parser.Int, binding.Optional), // Field: Value (*int)

	)
}

func (s *TestBindPtrIntQueryRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Query, "value", parser.Int, binding.Required), // Field: Value (*int)

	)
}

func (s *TestBindIntHeaderOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Header, "X-Value", parser.Int, binding.Optional), // Field: Value (int)

	)
}

func (s *TestBindIntHeaderRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Header, "X-Value", parser.Int, binding.Required), // Field: Value (int)

	)
}

func (s *TestBindPtrIntHeaderOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Header, "X-Value", parser.Int, binding.Optional), // Field: Value (*int)

	)
}

func (s *TestBindPtrIntHeaderRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Header, "X-Value", parser.Int, binding.Required), // Field: Value (*int)

	)
}

func (s *TestBindIntCookieOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Cookie, "value", parser.Int, binding.Optional), // Field: Value (int)

	)
}

func (s *TestBindIntCookieRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Cookie, "value", parser.Int, binding.Required), // Field: Value (int)

	)
}

func (s *TestBindPtrIntCookieOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Cookie, "value", parser.Int, binding.Optional), // Field: Value (*int)

	)
}

func (s *TestBindPtrIntCookieRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Cookie, "value", parser.Int, binding.Required), // Field: Value (*int)

	)
}

func (s *TestBindIntPathOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Path, "value", parser.Int, binding.Optional), // Field: Value (int)

	)
}

func (s *TestBindIntPathRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Path, "value", parser.Int, binding.Required), // Field: Value (int)

	)
}

func (s *TestBindPtrIntPathOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Path, "value", parser.Int, binding.Optional), // Field: Value (*int)

	)
}

func (s *TestBindPtrIntPathRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Path, "value", parser.Int, binding.Required), // Field: Value (*int)

	)
}

func (s *TestBindBoolQueryOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Query, "value", parser.Bool, binding.Optional), // Field: Value (bool)

	)
}

func (s *TestBindBoolQueryRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Query, "value", parser.Bool, binding.Required), // Field: Value (bool)

	)
}

func (s *TestBindPtrBoolQueryOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Query, "value", parser.Bool, binding.Optional), // Field: Value (*bool)

	)
}

func (s *TestBindPtrBoolQueryRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Query, "value", parser.Bool, binding.Required), // Field: Value (*bool)

	)
}

func (s *TestBindBoolHeaderOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Header, "X-Value", parser.Bool, binding.Optional), // Field: Value (bool)

	)
}

func (s *TestBindBoolHeaderRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Header, "X-Value", parser.Bool, binding.Required), // Field: Value (bool)

	)
}

func (s *TestBindPtrBoolHeaderOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Header, "X-Value", parser.Bool, binding.Optional), // Field: Value (*bool)

	)
}

func (s *TestBindPtrBoolHeaderRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Header, "X-Value", parser.Bool, binding.Required), // Field: Value (*bool)

	)
}

func (s *TestBindBoolCookieOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Cookie, "value", parser.Bool, binding.Optional), // Field: Value (bool)

	)
}

func (s *TestBindBoolCookieRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Cookie, "value", parser.Bool, binding.Required), // Field: Value (bool)

	)
}

func (s *TestBindPtrBoolCookieOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Cookie, "value", parser.Bool, binding.Optional), // Field: Value (*bool)

	)
}

func (s *TestBindPtrBoolCookieRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Cookie, "value", parser.Bool, binding.Required), // Field: Value (*bool)

	)
}

func (s *TestBindBoolPathOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Path, "value", parser.Bool, binding.Optional), // Field: Value (bool)

	)
}

func (s *TestBindBoolPathRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Path, "value", parser.Bool, binding.Required), // Field: Value (bool)

	)
}

func (s *TestBindPtrBoolPathOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Path, "value", parser.Bool, binding.Optional), // Field: Value (*bool)

	)
}

func (s *TestBindPtrBoolPathRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Path, "value", parser.Bool, binding.Required), // Field: Value (*bool)

	)
}

func (s *TestBindInt64QueryOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Query, "value", parser.Int64, binding.Optional), // Field: Value (int64)

	)
}

func (s *TestBindPtrInt64PathRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Path, "value", parser.Int64, binding.Required), // Field: Value (*int64)

	)
}

func (s *TestBindUint32HeaderOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Header, "X-Value", parser.Uint32, binding.Optional), // Field: Value (uint32)

	)
}

func (s *TestBindPtrUint32CookieRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Cookie, "value", parser.Uint32, binding.Required), // Field: Value (*uint32)

	)
}

func (s *TestBindFloat64QueryOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Query, "value", parser.Float64, binding.Optional), // Field: Value (float64)

	)
}

func (s *TestBindPtrFloat64HeaderRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Header, "X-Value", parser.Float64, binding.Required), // Field: Value (*float64)

	)
}

func (s *TestBindComplex128CookieOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Cookie, "value", parser.Complex128, binding.Optional), // Field: Value (complex128)

	)
}

func (s *TestBindPtrComplex128PathRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Path, "value", parser.Complex128, binding.Required), // Field: Value (*complex128)

	)
}

func (s *TestBindUintptrQueryOptional) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Value, binding.Query, "value", parser.Uintptr, binding.Optional), // Field: Value (uintptr)

	)
}

func (s *TestBindPtrUintptrHeaderRequired) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.OnePtr(b, &s.Value, binding.Header, "X-Value", parser.Uintptr, binding.Required), // Field: Value (*uintptr)

	)
}

func (s *TestBindMixedFields) Bind(req *http.Request, pathVar func(string) string) error {
	b := binding.New(req, pathVar)
	return errors.Join(

		binding.One(b, &s.Name, binding.Query, "name", parser.String, binding.Required), // Field: Name (string)

		binding.OnePtr(b, &s.Age, binding.Query, "age", parser.Int, binding.Optional), // Field: Age (*int)

		binding.One(b, &s.SessionID, binding.Cookie, "session_id", parser.String, binding.Required), // Field: SessionID (string)

		binding.OnePtr(b, &s.AuthToken, binding.Header, "X-Auth-Token", parser.String, binding.Optional), // Field: AuthToken (*string)

		binding.One(b, &s.UserID, binding.Path, "userID", parser.String, binding.Required), // Field: UserID (string)

		binding.OnePtr(b, &s.IsEnabled, binding.Query, "enabled", parser.Bool, binding.Optional), // Field: IsEnabled (*bool)

		binding.One(b, &s.Factor, binding.Header, "X-Factor", parser.Float64, binding.Optional), // Field: Factor (float64)

	)
}
