// Code generated by minigo-gen-bindings. DO NOT EDIT.

package filepath

import (
	"path/filepath"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "path/filepath" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("path/filepath", map[string]any{
		"IsLocal":       filepath.IsLocal,
		"FromSlash":     filepath.FromSlash,
		"EvalSymlinks":  filepath.EvalSymlinks,
		"Separator":     filepath.Separator,
		"Match":         filepath.Match,
		"Glob":          filepath.Glob,
		"ToSlash":       filepath.ToSlash,
		"Split":         filepath.Split,
		"Join":          filepath.Join,
		"IsAbs":         filepath.IsAbs,
		"Abs":           filepath.Abs,
		"Walk":          filepath.Walk,
		"Clean":         filepath.Clean,
		"Rel":           filepath.Rel,
		"WalkDir":       filepath.WalkDir,
		"Base":          filepath.Base,
		"VolumeName":    filepath.VolumeName,
		"ListSeparator": filepath.ListSeparator,
		"HasPrefix":     filepath.HasPrefix,
		"Localize":      filepath.Localize,
		"SplitList":     filepath.SplitList,
		"Ext":           filepath.Ext,
		"Dir":           filepath.Dir,
	})
}
