// Code generated by minigo-gen-bindings. DO NOT EDIT.

package time

import (
	"time"

	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "time" package to the interpreter.
func Install(interp *minigo.Interpreter) {
	interp.Register("time", map[string]any{
		"RFC3339":                time.RFC3339,
		"Date":                   time.Date,
		"RFC822Z":                time.RFC822Z,
		"Sleep":                  time.Sleep,
		"AfterFunc":              time.AfterFunc,
		"Friday":                 time.Friday,
		"Saturday":               time.Saturday,
		"RFC822":                 time.RFC822,
		"July":                   time.July,
		"Since":                  time.Since,
		"Now":                    time.Now,
		"Layout":                 time.Layout,
		"ParseInLocation":        time.ParseInLocation,
		"UnixDate":               time.UnixDate,
		"RubyDate":               time.RubyDate,
		"Parse":                  time.Parse,
		"FixedZone":              time.FixedZone,
		"May":                    time.May,
		"Millisecond":            time.Millisecond,
		"Stamp":                  time.Stamp,
		"StampNano":              time.StampNano,
		"August":                 time.August,
		"UnixMicro":              time.UnixMicro,
		"ParseDuration":          time.ParseDuration,
		"March":                  time.March,
		"Monday":                 time.Monday,
		"TimeOnly":               time.TimeOnly,
		"After":                  time.After,
		"February":               time.February,
		"November":               time.November,
		"Sunday":                 time.Sunday,
		"Kitchen":                time.Kitchen,
		"Minute":                 time.Minute,
		"StampMicro":             time.StampMicro,
		"September":              time.September,
		"Tuesday":                time.Tuesday,
		"Nanosecond":             time.Nanosecond,
		"RFC1123Z":               time.RFC1123Z,
		"StampMilli":             time.StampMilli,
		"DateTime":               time.DateTime,
		"Until":                  time.Until,
		"January":                time.January,
		"December":               time.December,
		"DateOnly":               time.DateOnly,
		"NewTicker":              time.NewTicker,
		"LoadLocationFromTZData": time.LoadLocationFromTZData,
		"April":                  time.April,
		"Second":                 time.Second,
		"NewTimer":               time.NewTimer,
		"Unix":                   time.Unix,
		"Wednesday":              time.Wednesday,
		"Thursday":               time.Thursday,
		"RFC1123":                time.RFC1123,
		"RFC3339Nano":            time.RFC3339Nano,
		"UnixMilli":              time.UnixMilli,
		"June":                   time.June,
		"October":                time.October,
		"Microsecond":            time.Microsecond,
		"Hour":                   time.Hour,
		"ANSIC":                  time.ANSIC,
		"RFC850":                 time.RFC850,
		"Tick":                   time.Tick,
		"LoadLocation":           time.LoadLocation,
	})
}
