// Code generated by minigo-gen-bindings. DO NOT EDIT.

package time

import (
	"time"
	"github.com/podhmo/go-scan/minigo"
)

// Install binds all exported symbols from the "time" package to the interpreter.
func Install(interp *minigo.Interpreter, installed map[string]bool) {
	if installed["time"] {
		return
	}
	installed["time"] = true

	interp.Register("time", map[string]any{
		"RFC850": time.RFC850,
		"NewTicker": time.NewTicker,
		"Since": time.Since,
		"December": time.December,
		"ANSIC": time.ANSIC,
		"StampMicro": time.StampMicro,
		"StampNano": time.StampNano,
		"Now": time.Now,
		"August": time.August,
		"Sunday": time.Sunday,
		"Minute": time.Minute,
		"UnixDate": time.UnixDate,
		"After": time.After,
		"Layout": time.Layout,
		"June": time.June,
		"RFC822Z": time.RFC822Z,
		"UnixMilli": time.UnixMilli,
		"ParseInLocation": time.ParseInLocation,
		"April": time.April,
		"RFC1123Z": time.RFC1123Z,
		"Kitchen": time.Kitchen,
		"StampMilli": time.StampMilli,
		"LoadLocation": time.LoadLocation,
		"RFC3339Nano": time.RFC3339Nano,
		"Date": time.Date,
		"May": time.May,
		"Wednesday": time.Wednesday,
		"Unix": time.Unix,
		"February": time.February,
		"TimeOnly": time.TimeOnly,
		"NewTimer": time.NewTimer,
		"September": time.September,
		"Saturday": time.Saturday,
		"RubyDate": time.RubyDate,
		"Tick": time.Tick,
		"UnixMicro": time.UnixMicro,
		"Tuesday": time.Tuesday,
		"Nanosecond": time.Nanosecond,
		"Microsecond": time.Microsecond,
		"LoadLocationFromTZData": time.LoadLocationFromTZData,
		"Friday": time.Friday,
		"Millisecond": time.Millisecond,
		"July": time.July,
		"October": time.October,
		"Thursday": time.Thursday,
		"RFC822": time.RFC822,
		"DateTime": time.DateTime,
		"FixedZone": time.FixedZone,
		"November": time.November,
		"Monday": time.Monday,
		"Second": time.Second,
		"Hour": time.Hour,
		"Until": time.Until,
		"Parse": time.Parse,
		"January": time.January,
		"RFC1123": time.RFC1123,
		"Stamp": time.Stamp,
		"Sleep": time.Sleep,
		"AfterFunc": time.AfterFunc,
		"ParseDuration": time.ParseDuration,
		"March": time.March,
		"RFC3339": time.RFC3339,
		"DateOnly": time.DateOnly,
	})
}
